pipeline:
  name: DS - Build All w Docker Delegate
  identifier: DS_Build_All_w_Docker_Delegate
  projectIdentifier: demo_skills_project
  orgIdentifier: default
  tags: {}

  properties:
    ci:
      codebase:
        connectorRef: git_proj_demoskills
        build: <+input>

  variables:
    - name: TARGET_ENV
      type: String
      value: <+input>.allowedValues(Development,Production)
      description: Target environment passed into child builds (ASPNETCORE_ENVIRONMENT)
      required: true
      default: Development
    - name: PERFORM_TESTS
      type: String
      value: <+input>.allowedValues("Yes","No")
      description: Run tests in child builds? Yes to run, No to skip
      required: true
      default: "Yes"

  stages:
    - stage:
        name: Build Matrix
        identifier: Build_Matrix
        type: Pipeline
        strategy:
          matrix:
            service:
              - EmployeeAPI
              - CompanyAPI
              - TaxCalculatorAPI
              - PayAPI
              - ReportAPI
              - Dashboard
        spec:
          pipeline: DS_Build_w_Docker_Delegate
          inputs:
            variables:
              SERVICE_NAME: <+matrix.service>
              TARGET_ENV: <+pipeline.variables.TARGET_ENV>
              PERFORM_TESTS: <+pipeline.variables.PERFORM_TESTS>
