services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/demoskills.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - postgres
      - dashboard
      - employeeapi
      - companyapi
      - payapi
      - taxcalculatorapi
      - reportapi

  dashboard:
    build:
      context: ./dashboard
    image: demoskills-dashboard:local

  employeeapi:
    build:
      context: ./apis/EmployeeAPI
    image: demoskills-employeeapi:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=${DEMOSKILLS_POSTGRES_DB?};Username=${DEMOSKILLS_POSTGRES_USER?};Password=${DEMOSKILLS_POSTGRES_PASSWORD?}
    depends_on:
      - postgres

  companyapi:
    build:
      context: ./apis/CompanyAPI
    image: demoskills-companyapi:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL: postgresql+psycopg://${DEMOSKILLS_POSTGRES_USER?}:${DEMOSKILLS_POSTGRES_PASSWORD?}@postgres:5432/${DEMOSKILLS_POSTGRES_DB?}
    depends_on:
      - postgres

  payapi:
    build:
      context: ./apis/PayAPI
    image: demoskills-payapi:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=${DEMOSKILLS_POSTGRES_DB?};Username=${DEMOSKILLS_POSTGRES_USER?};Password=${DEMOSKILLS_POSTGRES_PASSWORD?}
    depends_on:
      - postgres

  taxcalculatorapi:
    build:
      context: ./apis/TaxCalculatorAPI
    image: demoskills-taxcalculatorapi:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=${DEMOSKILLS_POSTGRES_DB?};Username=${DEMOSKILLS_POSTGRES_USER?};Password=${DEMOSKILLS_POSTGRES_PASSWORD?}
    depends_on:
      - postgres

  reportapi:
    build:
      context: ./apis/ReportAPI
    image: demoskills-reportapi:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL: postgresql+psycopg://${DEMOSKILLS_POSTGRES_USER?}:${DEMOSKILLS_POSTGRES_PASSWORD?}@postgres:5432/${DEMOSKILLS_POSTGRES_DB?}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: demoskills-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DEMOSKILLS_POSTGRES_DB?}
      POSTGRES_USER: ${DEMOSKILLS_POSTGRES_USER?}
      POSTGRES_PASSWORD: ${DEMOSKILLS_POSTGRES_PASSWORD?}
    volumes:
      - demoskills_pgdata:/var/lib/postgresql/data

  dozzle:
    image: amir20/dozzle:v8.10.2
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  demoskills_pgdata:
