proxy_http_version 1.1;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Connection "";

upstream employeeapi {
    server employeeapi:8080;
}

upstream companyapi {
    server companyapi:8081;
}

upstream payapi {
    server payapi:8082;
}

upstream taxcalculatorapi {
    server taxcalculatorapi:8083;
}

upstream reportapi {
    server reportapi:8084;
}

upstream dashboard {
    server dashboard:80;
}

server {
    listen 80;
    server_name _;

    location /employee/ {
        proxy_pass http://employeeapi/;
    }

    location /company/ {
        proxy_pass http://companyapi/;
    }

    location /pay/ {
        proxy_pass http://payapi/;
    }

    location /tax/ {
        proxy_pass http://taxcalculatorapi/;
    }

    location /report/ {
        proxy_pass http://reportapi/;
    }

    location / {
        proxy_pass http://dashboard;
    }
}
