JWT_AUTHORITY_ENV = "Jwt__Authority"
JWT_CLIENT_ID_ENV = "Jwt__ClientId"

CLAIM_TOKEN_USE = "token_use"
CLAIM_CLIENT_ID = "client_id"
CLAIM_GROUPS = "cognito:groups"
CLAIM_SUB = "sub"
CLAIM_EMAIL = "email"

GROUP_INTERNAL_ADMIN = "internal_admin"
GROUP_INTERNAL_SUPPORT = "internal_support"
GROUP_EXTERNAL_USER = "external_user"
GROUP_EXTERNAL_EMPLOYEE = "external_employee"

GROUP_PRECEDENCE_INTERNAL_ADMIN = 100
GROUP_PRECEDENCE_INTERNAL_SUPPORT = 300
GROUP_PRECEDENCE_EXTERNAL_USER = 500
GROUP_PRECEDENCE_EXTERNAL_EMPLOYEE = 700

PERMISSION_COMPANY_CREATE = "company-create"
PERMISSION_COMPANY_READ = "company-read"
PERMISSION_COMPANY_UPDATE = "company-update"
PERMISSION_COMPANY_DELETE = "company-delete"

PERMISSION_PAY_VIEW = "pay-view"
PERMISSION_PAY_CREATE = "pay-create"
PERMISSION_PAY_PROCESS = "pay-process"
PERMISSION_PAY_CLOSE = "pay-close"
PERMISSION_PAY_DELETE = "pay-delete"

PERMISSION_EMPLOYEE_READ = "employee-read"
PERMISSION_EMPLOYEE_CREATE = "employee-create"
PERMISSION_EMPLOYEE_UPDATE = "employee-update"
PERMISSION_EMPLOYEE_DELETE = "employee-delete"

PERMISSION_TAX_READ = "tax-read"
PERMISSION_REPORT_READ = "report-read"
