JWT_AUTHORITY_ENV = "Jwt__Authority"
JWT_CLIENT_ID_ENV = "Jwt__ClientId"

CLAIM_TOKEN_USE = "token_use"
CLAIM_CLIENT_ID = "client_id"
CLAIM_GROUPS = "cognito:groups"
CLAIM_SUB = "sub"
CLAIM_EMAIL = "email"

GROUP_INTERNAL_ADMIN = "internal_admin"
GROUP_INTERNAL_SUPPORT = "internal_support"
GROUP_EXTERNAL_USER = "external_user"
GROUP_EXTERNAL_EMPLOYEE = "external_employee"

GROUP_PRECEDENCE_INTERNAL_ADMIN = 100
GROUP_PRECEDENCE_INTERNAL_SUPPORT = 300
GROUP_PRECEDENCE_EXTERNAL_USER = 500
GROUP_PRECEDENCE_EXTERNAL_EMPLOYEE = 700
