from .constants import (
    GROUP_EXTERNAL_EMPLOYEE,
    GROUP_EXTERNAL_USER,
    GROUP_INTERNAL_ADMIN,
    GROUP_INTERNAL_SUPPORT,
    GROUP_PRECEDENCE_EXTERNAL_EMPLOYEE,
    GROUP_PRECEDENCE_EXTERNAL_USER,
    GROUP_PRECEDENCE_INTERNAL_ADMIN,
    GROUP_PRECEDENCE_INTERNAL_SUPPORT,
)


def get_group_precedence(group: str | None) -> int | None:
    if group == GROUP_INTERNAL_ADMIN:
        return GROUP_PRECEDENCE_INTERNAL_ADMIN
    if group == GROUP_INTERNAL_SUPPORT:
        return GROUP_PRECEDENCE_INTERNAL_SUPPORT
    if group == GROUP_EXTERNAL_USER:
        return GROUP_PRECEDENCE_EXTERNAL_USER
    if group == GROUP_EXTERNAL_EMPLOYEE:
        return GROUP_PRECEDENCE_EXTERNAL_EMPLOYEE
    return None
