
### --- Employee ---
### 8080 is blocked on longranch.com
GET http://longranch.com:8080/api/v1/employees/health
### 80 is allowed. this it the load balancer.
GET http://longranch.com:80/api/v1/employees/health
### health no port
GET http://longranch.com/api/v1/employees/health
### swagger
GET http://longranch.com/api/v1/employees/swagger
### swagger
GET http://longranch.com/employees/swagger
### health
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/api/v1/employees/health
### swagger
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/employees/swagger

### --- Company ---
### 8081 is blocked on longranch.com
GET http://longranch.com:8081/api/v1/companies/health
### 80 is allowed. this it the load balancer.
GET http://longranch.com:80/api/v1/companies/health
### 
GET http://longranch.com/api/v1/companies/health
### 
GET http://longranch.com/api/v1/companies
### doc (py swagger)
GET http://longranch.com/companies/swagger
### doc (py swagger)
GET http://longranch.com/companies/docs
### operations (health)
GET http://longranch.com/companies/ops
### 
GET http://longranch.com/companies/openapi.json
