### Base domain (reserved for UI/gateway later)
GET http://longranch.com


### Employee
GET http://employee.longranch.com/api/v1/employees/health
###
GET http://employee.longranch.com/swagger
###
GET http://employee.longranch.com/swagger/v1/swagger.json


### Pay
GET http://pay.longranch.com/api/v1/pay/health
###
GET http://pay.longranch.com/swagger
###
GET http://pay.longranch.com/swagger/v1/swagger.json


### Tax via PayAPI
GET http://tax.longranch.com/api/v1/taxes/health
###
GET http://tax.longranch.com/swagger
###
GET http://tax.longranch.com/swagger/v1/swagger.json



### Company via EmployeeAPI
GET http://company.longranch.com/api/v1/companies/health
###
GET http://company.longranch.com/api/v1/companies
###
GET http://company.longranch.com/swagger
###
GET http://company.longranch.com/swagger/v1/swagger.json



### Report
GET http://report.longranch.com/api/v1/reports/health
###
GET http://report.longranch.com/swagger
###
GET http://report.longranch.com/swagger/v1/swagger.json
