
### --- Employee ---
### 8080 is blocked on longranch.com
GET http://longranch.com:8080/api/v1/employees/health
### 80 is allowed. this it the load balancer.
GET http://longranch.com:80/api/v1/employees/health
###
GET http://longranch.com/api/v1/employees/health
###
GET http://longranch.com/swagger/index.html
###
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/api/v1/employees/health
###
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/swagger/index.html

### --- Company ---
### 8081 is blocked on longranch.com
GET http://longranch.com:8081/health
### 80 is allowed. this it the load balancer.
GET http://longranch.com:80/health
### 
GET http://longranch.com/health 
###
GET http://longranch.com/swagger/index.html
###
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/health
###
GET http://demoskills-alb-1952058927.us-east-1.elb.amazonaws.com/swagger/index.html